#!/usr/bin/env python3
"""Bake a static, crawler-visible snapshot of the theme ledger into the themes page.

The interactive ledger renders client-side from themes.json, which leaves the
page at ~100 visible words for anything that does not execute JavaScript —
including every major AI crawler. This script writes a plain-HTML summary of
every theme between AUTO:THEMES_STATIC markers inside the #themes-live mount.
Browsers replace it the moment trading-themes.js renders; crawlers read it.

Run this AFTER any edit to trading/themes.json, then commit both files.
It also restamps the themes.json ?v= hash on the page, so no separate restamp
step is needed. test-trading-themes.py fails loudly if page and data drift.
"""
from __future__ import annotations

import hashlib
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "trading" / "themes.json"
PAGE = ROOT / "trading" / "themes" / "index.html"
START = "<!-- AUTO:THEMES_STATIC:START"
END = "<!-- AUTO:THEMES_STATIC:END -->"


def esc(value) -> str:
    return html.escape(str(value or ""), quote=True)


def gap_of(scores) -> int:
    return int(scores["knowledge_saturation"]) - int(scores["price_saturation"])


def render_static(payload: dict, data_hash: str) -> str:
    all_themes = sorted(payload["themes"], key=lambda t: gap_of(t["consensus_scores"]), reverse=True)
    qualified = [theme for theme in all_themes if theme.get("qualified") and not theme.get("disqualified")]
    themes = [theme for theme in all_themes if not theme.get("disqualified") and not theme.get("qualified")]
    disqualified = [theme for theme in all_themes if theme.get("disqualified")]
    cats: dict[str, int] = {}
    for theme in themes:
        cats[theme["category"]] = cats.get(theme["category"], 0) + 1
    cat_line = " · ".join(f"{name} {count}" for name, count in sorted(cats.items()))

    blocks = [
        f"{START} sha256[:12]({DATA.name})={data_hash} — generated by scripts/build-themes-static.py; do not hand-edit -->",
        '<section class="themes-static themes-static-core">',
        "<h2>Core themes</h2>",
        f"<p>{len(themes)} active investment themes, each scored 0–100 for how widely <strong>known</strong> the story is "
        f"and how fully <strong>priced</strong> it already is. The gap between the two is the signal. "
        f"Categories: {esc(cat_line)}. Scores are the median of named AI-model reviews "
        f"(Claude Fable 5, GPT-5.6, Grok 4.5, Gemini, Meta); missing scores are never invented. "
        f"{len(qualified)} qualified {'theme backs' if len(qualified) == 1 else 'themes back'} live desk positions (listed below, before the graveyard). "
        f"{len(disqualified)} disqualified {'theme is' if len(disqualified) == 1 else 'themes are'} retained below so rejected ideas are not recreated. "
        f'Full records, adversarial reviews, falsifiers and sources are in the interactive ledger and in '
        f'<a href="/trading/themes.json">themes.json</a>.</p>',
    ]

    def append_theme(theme: dict, *, show_disqualification: bool = False, show_qualification: bool = False) -> None:
        scores = theme["consensus_scores"]
        gap = gap_of(scores)
        assert {"knowledge_saturation", "price_saturation"} <= set(scores), theme["id"]
        reviewers = ", ".join(theme.get("reviewed_by") or []) or "none yet"
        disqualification = ""
        if show_disqualification:
            details = theme["disqualified"]
            symbols = " · ".join(details["symbols"])
            disqualification = (
                f'<p class="ts-disqualification"><strong>Disqualified:</strong> {esc(details["reason"])} '
                f'<strong>Flagged tickers:</strong> {esc(symbols)}</p>\n'
            )
        if show_qualification:
            details = theme["qualified"]
            disqualification = (
                f'<p class="ts-qualification"><strong>Qualified:</strong> {esc(details["note"])} '
                f'<strong>Position:</strong> {esc(details["position"])} · {esc(details["date"])}</p>\n'
            ) + disqualification
        blocks.append(
            f'<article id="static-{esc(theme["id"])}">\n'
            f'<h2><a href="/trading/themes/#{esc(theme["id"])}">{esc(theme["title"])}</a></h2>\n'
            f'<p class="ts-meta">{esc(theme["category"])} · {esc(theme["horizon"])} · {esc(theme["status"])} · '
            f'known {scores["knowledge_saturation"]} / priced {scores["price_saturation"]} / gap {"+" if gap > 0 else ""}{gap} · '
            f'sourced by {esc(theme["source_model"])} · reviewed by {esc(reviewers)}</p>\n'
            f'{disqualification}'
            f'<p>{esc(theme["owner_belief"])}</p>\n'
            f'<p><strong>Verdict:</strong> {esc(theme["final_verdict"])}</p>\n'
            f"</article>"
        )

    for theme in themes:
        append_theme(theme)
    blocks.append("</section>")
    if qualified:
        blocks.extend([
            '<section class="themes-static themes-static-qualified">',
            "<h2>Qualified themes</h2>",
            "<p>Graduated from research to live desk positions. Scores stay frozen at qualification; the position note records what was bought and when.</p>",
        ])
        for theme in qualified:
            append_theme(theme, show_qualification=True)
        blocks.append("</section>")
    if disqualified:
        blocks.extend([
            '<section class="themes-static themes-static-disqualified">',
            "<h2>Disqualified themes</h2>",
            "<p>Retained so rejected ideas do not get recreated.</p>",
        ])
        for theme in disqualified:
            append_theme(theme, show_disqualification=True)
        blocks.append("</section>")
    blocks.append(END)
    return "\n".join(blocks)


def main() -> None:
    payload = json.loads(DATA.read_text())
    data_hash = hashlib.sha256(DATA.read_bytes()).hexdigest()[:12]
    page = PAGE.read_text()

    static = render_static(payload, data_hash)
    if START in page:
        pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
        assert len(pattern.findall(page)) == 1
        page = pattern.sub(lambda _: static, page)
    else:
        # First run: place inside the mount, replacing the loading placeholder
        # so crawlers see content and the JS app replaces it on render.
        anchor = re.search(r'(<main id="themes-live"[^>]*>)(.*?)(</main>)', page, re.S)
        assert anchor, "themes mount not found"
        page = page[: anchor.start(2)] + "\n" + static + "\n" + page[anchor.end(2):]

    # Restamp the data URL so page and JSON always move together.
    page, n = re.subn(r"themes\.json\?v=[a-f0-9]{12}", f"themes.json?v={data_hash}", page)
    assert n >= 1, "themes.json ?v= stamp not found"

    PAGE.write_text(page)
    words = len(re.findall(r"\b\w+\b", re.sub(r"<[^>]+>", " ", static)))
    print(f"[themes-static] {len(payload['themes'])} themes baked · ~{words} words · data hash {data_hash}")


if __name__ == "__main__":
    main()
